sbdchd/neoformat

- doc/neoformat.txt
The doc contains duplicate tags, which breaks NeoBundle install.
> Remove duplicate tags `*neoformat*`

- README.md
- autoload/neoformat/formatters/pandoc.vim
- doc/neoformat.txt
We can use Pandoc to format Pandoc-flavored Markdown.
The extra flags handle bare URLs not being escaped correctly and
non-standard Markdown headers.
We pipe to `sed` to fix incorrect bracket escaping since Pandoc does not
support the check box feature of Github Markdown.
> Add Pandoc formatter

- autoload/neoformat/run.vim
Tested on neovim:HEAD
**Didn't test** on VIM, but I don't see where I would affect it
> Fixes #7. on_stdout, on_stderr and on_stdexit always require 3 parameters

- doc/neoformat.txt
Dein.vim was complaining about duplicate tags in your doc file, so I removed the second `Neoformat` tag.
```
[dein] Error generating helptags:
[dein] Vim(helptags):E154: Duplicate tag "Neoformat" in file /Users/mhartington/.config/nvim/.cache/init.vim/.dein/doc/neoformat.txt
[dein] function dein#end[1]..dein#util#_end[39]..dein#recache_runtimepath[1]..dein#install#_recache_runtimepath[20]..<SNR>9_helptags, line 12
```
> fix(doc): remove duplicate tag

- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/html.vim
- autoload/neoformat/formatters/javascript.vim
- autoload/neoformat/formatters/scss.vim
Hi! If the user had settings for `shiftwidth`, the formatter should respect this. 
I went and added it for html,css,scss, and js (what I use most of the time.
🍻
> fix(html,css,js,scss): user indent settings

- autoload/neoformat/formatters/haskell.vim
The `=` isn't parsed by `hindent` and gives an error.
> Fix hindent args

- README.md
- autoload/neoformat.vim
- doc/neoformat.txt
- test/after/cssbeautify-indent-6.css
- test/autocomplete_test.vim
- test/test.py
With `let g:neoformat_try_formatprg = 1`
Neoformat will try &formatprg before finding other formatter definitions
See https://github.com/sbdchd/neoformat/issues/36
> Add g:neoformat_try_formatprg

- autoload/neoformat/formatters/haskell.vim
stylish-haskell doesn't seem to always handle errors correctly
> restore stylish-haskell redirect to /dev/null

- autoload/neoformat/formatters/ruby.vim
This patch adds support for Rubocop for auto-correcting style problems. Rubocop is the de-facto standard for code styling and formatting in Ruby. 
Currently, Rubocop always prepends some metadata about the errors that we have to filter out with `sed` (see https://github.com/bbatsov/rubocop/issues/2502). In the future, there may be an option to allow us to avoid doing this.
> Add rubocop formatter for ruby

- README.md
- autoload/neoformat/formatters/tex.vim
- doc/neoformat.txt
This patch adds a formatter for LaTeX. Unfortunately, when using the version latexindent bundled with TeX Live and a newer version of perl, it spits a handful of deprecation warnings out. I resolved this by manually calling the script from perl with the X flag. If there is a way to ignore stdout and only read the file, that would be better solution, however this works as-is.
> Add latexindent formatter

- autoload/neoformat/formatters/markdown.vim
`remark: 7.0.0` and `remark-cli: 3.0.0` doesn't support stdin method
```
Neoformat: ['<stdin>', '  1:1  error  TypeError: Path must be a string. Received undefined' ...
```
so use `/tmp/neoformat` instead.
> remark: fix stdin issue

- autoload/neoformat/formatters/pandoc.vim
This causes any lines with colons to be treated as title blocks, which
leads to some nasty shocks when formatting.
> Remove `mmd_title_block` from Pandoc formatter

- README.md
- autoload/neoformat/formatters/javascript.vim
- doc/neoformat.txt
eslint_d is the only sane way to do autofixing on Vim with Eslint in terms of speed and battery usage.
Fixing https://github.com/mantoni/eslint_d.js/issues/64
> add eslint_d support

- autoload/neoformat.vim
Quick and dirty fix for #69. It seems that #66 will require more work for working cross platform on Windows machines - I don't have access to one, but this should ensure no errors on OSX and Linux.
I'm not familiar with testing for vim plugins, but am happy to add some if someone points me in the right direction.
> Check for existing tmp dir before creation

- README.md
Previous commit e93653d introduced rubocop as one of Ruby's supported
formatters. This commit adds it to README.md for users to see.
> Update readme for rubocop

- autoload/neoformat/formatters/css.vim
- test/after/prettydiff.css
This uses the commandline args to set the indentsize (that defaults to 4 spaces).
> Update css.vim: set indent size for prettydiff

- autoload/neoformat/utils.vim
Dunno if this is different in neovim, but in vim 7.4 if you do
`:let foo = []`
`:let foo = ''`
You'll get the following error: 
`E706: Variable type mismatch for: foo`
This means that if you call `better_echo(['some string'])` it will fail with that error.
> Fix a type mismatch error in better_echo

- autoload/neoformat.vim
I was running into errors when using `prettier` on javascript files. Turns out [system()](http://vimdoc.sourceforge.net/htmldoc/eval.html#system()) was expecting `stdin` to be a string, but [getbufline()](http://vimdoc.sourceforge.net/htmldoc/eval.html#getbufline()) returns a list.
> Fix type of stdin argument to system()

- README.md
- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/less.vim
- autoload/neoformat/formatters/scss.vim
The 1.4.0 release of prettier added support for css, less and scss: https://github.com/prettier/prettier/releases/tag/1.4.0
I also took the liberty to fix some minor issues in the README, hope you don't mind.
> Add 'prettier' support for css, less and scss

- README.md
- autoload/neoformat/formatters/ruby.vim
- doc/neoformat.txt
This enables `https://github.com/asterite/rufo` as a formatter for ruby. It's damn fast and awesome. Thanks @asterite. And thanks @sbdchd for neoformat :)
> Add rufo ruby formatter

- README.md
- doc/neoformat.txt
I run Neoformat on save, and I save automatically on `CursorHold`. That means that I don't have to even think about formatting or saving. But the combination does load to a frustrating experience where I have to tap `u` quickly twice to undo any change that leads to a formatting change. I finally did enough research to learn about the `undo-blocks` feature in Vim / Neovim, which provides a perfect solution for my situation! I wanted to share what I learned with other Neoformat users.
> Add notes to docs about using `undojoin` to skip over formatting changes on undo

- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/less.vim
- autoload/neoformat/formatters/scss.vim
- doc/neoformat.txt
For Less and SCSS, the `prettier` formatters are already defined, but they are not in the list. I just added it.
> Add `prettier` to the list of formatters for Less/SCSS

- autoload/neoformat/formatters/perl.vim
This prevents an error message being printed to standard error when `perltidy` has a problem parsing the file. Without this, you end up with the error message at the top of your source code.
Currently, neoformat cannot tell that `perltidy` had an error as the exit code is 0 on error.  Related #94.
> Do not print error description at the top of file

- README.md
- autoload/neoformat/formatters/elm.vim
- autoload/neoformat/formatters/reason.vim
- doc/neoformat.txt
Reason is a OCaml based language from Facebook. It comes with a
formatter called `refmt`, which all all Reason code is expected to be
formatted with. This adds support for this formatter.
> Reason ML support

- autoload/neoformat.vim
i use gvim on windows.
it had a bug of temp dir as  `/tmp/neoformat`.
this path will make some dir like `X:\tmp\neoformat` for each partition when i edit file on different disk.
i modified the code, distinguish between windows and unix.
here is a PR.
thanks.
> fix bug with temp dir on windows.

- autoload/neoformat.vim
i'm so sorry for last RP had a bug about $TMPDIR.
because i used plugin `w0rp/ale` have set $TMPDIR if this env var is not exists.
> fix bug when $TMPDIR is not set on unix.

- README.md
- autoload/neoformat/formatters/graphql.vim
- doc/neoformat.txt
Prettier supports GraphQL parsing now, so we can use it to format graphql filetypes.
> Add prettier formatter for GraphQL

- autoload/neoformat/formatters/css.vim
This avoids the following warning when using prettier `>=1.7.0`
```
`--parser` with value `postcss` is deprecated. Prettier now treats it as: `--parser=css`.
```
> Update prettier options for CSS formatting

- autoload/neoformat/formatters/javascript.vim
`prettier` and `prettier-eslint` both look for configuration files relative to the formated file path (a Prettier configuration for both, and a ESLint configuration for `prettier-eslint`).
Using the `--stdin-filepath` option will make both commands using the expected configuration files instead of the ones relative to the current directory.
> Define filepath for prettier and prettiereslint (#112)

- README.md
- autoload/neoformat/formatters/elixir.vim
- doc/neoformat.txt
This PR proposes adding the new official Elixir code formatter, that will be part of the upcoming release (it is already available in `master` builds).
Tested with `mix format` on `master` Elixir.
> Add `mix format` formatter for Elixir

- README.md
- autoload/neoformat/formatters/json.vim
- doc/neoformat.txt
[fixjson](https://github.com/rhysd/fixjson) is a JSON file fixer/formatter for humans using (relaxed) JSON5. It formats a JSON code and fixes some trivial errors at the same time.
I added a configuration of neoformat for fixjson.
> Add built-in support for fixjson

- autoload/neoformat/formatters/ruby.vim
Rufo exits with code `3` on a successfull change. See https://github.com/ruby-formatter/rufo#exit-codes. This change configures neoformat to allow that exitcode.
> Allow exit code 3 from rufo

- autoload/neoformat/formatters/ocaml.vim
ocamlformat reads optional configuration from a .ocamlformat file in the source tree.
But Neoformat called ocamlformat with a temporary file path in /tmp, so it never found those configuration files.
Tell ocamlformat the real path of the file so it can load its configuration.
> ocamlformat: obey .ocamlformat configuration

- autoload/neoformat/formatters/haskell.vim
Project specific configuration had been overwritten by this args. Also, hindent has default line length and it's 80(see https://github.com/commercialhaskell/hindent#customization).
> Drop default line length for hindent

- README.md
- autoload/neoformat/formatters/sql.vim
- doc/neoformat.txt
`sqlformat` from sqlparse [has issues](https://github.com/andialbrecht/sqlparse/issues/360#issuecomment-379706669) with reindenting SQL files containing `create table` statements.
`pg_format` from [pgFormatter](https://github.com/darold/pgFormatter) appears to do better, at least for this case.
> Add another SQL option: pg_format from pgFormatter

- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/graphql.vim
- autoload/neoformat/formatters/json.vim
- autoload/neoformat/formatters/typescript.vim
- autoload/neoformat/formatters/vue.vim
When using `prettier` with `--stdin`, it is _always_ needed to also pass `--stdin-filepath`, or it will not be able to figure out custom settings like EditorConfig.
This was done for javascript in earlier PR https://github.com/sbdchd/neoformat/pull/119, but this has to be done for every single file type.
References: https://github.com/prettier/prettier/issues/4351, https://github.com/sbdchd/neoformat/issues/105#issuecomment-383250126
> Make sure `--stdin-filepath` is always provided for prettier

- autoload/neoformat/formatters/typescript.vim
Fixes #159. The objection to 4472665 in #37 was that it resulted in tsfmt.json not being respected, which was due to the `tsfmt` call being run on the tmp file, divorced from the tree structure of the original file. Using the `baseDir` option solves this concern.
> Switch tsfmt back to --replace option. Fixes #159

- README.md
- autoload/neoformat.vim
- autoload/neoformat/utils.vim
- doc/neoformat.txt
I've added checking for `b:` configuration variables. I use `yapf` as my python formatter, but it cannot sort imports. Therefore, for python, and python only I would like to run all enabled formatters, `yapf` and `isort`.
For example, not it is possible to do following.
```viml
let g:neoformat_enabled_python = ['yapf', 'isort']
let g:neoformat_run_all_formatters = 0
augroup filetype_python
autocmd!
autocmd FileType python let b:neoformat_run_all_formatters = 1
augroup END
```
Note to README and documentation was added, but I didn't run tests because it couldn't set up testing environment. I am open to provide dedicated Dockerfile for testing purposes, if requested.
> Adds local-to-buffer configuration support

- autoload/neoformat/formatters/javascript.vim
Without this, using prettier within eslint within eslint_d sometimes throws [No parser could be inferred for file](https://github.com/prettier/prettier/blob/b8ded708485c101e467b37bdb45bca520dd267ef/src/main/options.js#L43).
> Fix eslint_d file type detection

- README.md
- autoload/neoformat/formatters/python.vim
- doc/neoformat.txt
[Pydevf](https://github.com/fabioz/PyDev.Formatter) is formatter extracted as commandline utility from pydev by its creator.
> Add pydevf as python formatter

- autoload/neoformat/formatters/reason.vim
The previous configuration assumed that ReasonML files would always be
implementation files rather than interfaces files, so it would not be
able to format all files in a project.
The same may need to be done for OCaml.
> Support ReasonML interface files

- autoload/neoformat/formatters/python.vim
The extra isort command line flags added by https://github.com/sbdchd/neoformat/pull/154 are preventing my own projects' isort settings from taking effect.
Having them as command line arguments in neoformat means that they are dictating someone else's isort style preferences, and they cannot be overridden by any configuration files since command line arguments take precedence. This PR removes them.
If someone prefers having `use-parantheses` and/or `trailing-comma` enabled, they should do so through one of the several configuration files that [isort supports](https://github.com/timothycrosley/isort#configuring-isort) at the project-level (eg, `setup.cfg`, `.editorconfig`, `tox.ini`, etc.) or the user-level (`~/.isort.cfg`).
> Remove extraneous isort command line flags

- README.md
- autoload/neoformat.vim
- autoload/neoformat/formatters/haskell.vim
- autoload/neoformat/formatters/python.vim
- autoload/neoformat/formatters/ruby.vim
- autoload/neoformat/utils.vim
- doc/neoformat.txt
This should fix problem with logs printed on stderr being captured by vim's `system` call. Might be not best solution, it requires some thought if there is not a better way. Particularly, I see two issues with it, it might break formatters that are relying on stderr output (this can be fixed by setting `stderr` flag to 1 in formatter definition) and perhaps if given formatter relies on tricky redirection in `args`. By quick grep, I found that only three formatters make use of `2>/dev/null`, which could be removed if this get merged. Personally, I would like to have such log to inspect if there is no problem with my configuration or whatnot.
Another problem that can occur is that stderr is redirected to `stderr.log` file, and theoretically, this can pose problem if someone was formatting …
> Redirect stderr to log file by default

- README.md
- autoload/neoformat/formatters/php.vim
- doc/neoformat.txt
I saw that #54 lead to there being a feature added to handle non-standard error codes for `phpcbf`'s sake, figured I'd give adding `phpcbf` to the official formatters a shot.
> Added phpcbf to the available PHP formatters

- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/graphql.vim
- autoload/neoformat/formatters/javascript.vim
- autoload/neoformat/formatters/json.vim
- autoload/neoformat/formatters/markdown.vim
- autoload/neoformat/formatters/ocaml.vim
- autoload/neoformat/formatters/ruby.vim
- autoload/neoformat/formatters/typescript.vim
- autoload/neoformat/formatters/vue.vim
- autoload/neoformat/formatters/yaml.vim
When editing files with spaces in their paths neoformat often fails. Most annoying example is files within iCloud Drive on Mac: `~/Library/Mobile Documents/iCloud...`
> Escape spaces in file paths when running cli commands

- autoload/neoformat/formatters/ocaml.vim
Since https://github.com/ocaml-ppx/ocamlformat/pull/353 , ocamlformat can read from stdin. This provides a much tighter integration with neoformat (no ugly messages in vim's console).
I confirmed this works on my vim
> Smoother integration with OCamlformat

- autoload/neoformat/formatters/elm.vim
Currently, `elm-format` does not work well with Neoformat because it cannot detect a version of Elm which is currently used unless it's executed at the top directory containing `elm.json` for v0.19 or `elm-package.json` for v0.18. This PR makes it work with the latest version of 0.19 by passing Elm's verion explicitly as a command line argument.
> Stick with Elm v0.19

- autoload/neoformat/formatters/python.vim
I haven't had the opportunity to reproduce this on a Linux machine, but
on my Windows setup, running the Black formatter appends the pretty
summary to my buffer. The problem is solved by asking Black to be
'quiet'.
Example of the content appended to my buffer (prior to this change):
```
reformatted -
All done! \u2728 \U0001f370 \u2728
1 file reformatted.
```
> [Python]: Pass the 'quiet' argument to Black

- README.md
- autoload/neoformat/formatters/nim.vim
- doc/neoformat.txt
`nimpretty` is the formatter that comes bundles with [Nim][]! This PR adds support for it to Neoformat.
[Nim]: https://nim-lang.org/
> Add nimpretty as formatter for nim files

- README.md
- autoload/neoformat/formatters/r.vim
- autoload/neoformat/formatters/tex.vim
- doc/neoformat.txt
Fix error in https://github.com/sbdchd/neoformat/pull/217
**To enable all the formatters, please install these R packages: `sytler`, `formatR`, `readr`.**
> Fix formatter (styler) error and add new formatter (formatR) for R language

- README.md
- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/less.vim
- autoload/neoformat/formatters/sass.vim
- autoload/neoformat/formatters/scss.vim
- doc/neoformat.txt
Adds support for `stylelint --fix` which is [recommended by stylefmt](https://github.com/morishitter/stylefmt#notice-consider-other-tools-before-adopting-stylefmt)
> Support for stylelint --fix

- README.md
- doc/neoformat.txt
The `eslint_d` formatter for TypeScript wasn't previously documented. This adds that.
> docs(typescript): add `eslint_d` docs

- README.md
- doc/neoformat.txt
[JavaScript](https://www.javascript.com) and [TypeScript](https://www.typescriptlang.org) were previously improperly capitalized.
_edit_: formatting
> docs: capitalize JavaScript, TypeScript

- autoload/neoformat/formatters/typescript.vim
I had previously recorded the clang-format definition for JavaScript and
improperly recorded the clang-format formatter name as `clang-format`
rather than `clangformat` as it is in the formatter definition. This
fixes that.
> fix(typescript): fix clang-format definition

- autoload/neoformat/formatters/typescript.vim
Use `--force` to make sure `tslint` always returns status code `0` when exitting.
> fix tslint formatter when one or more errors couldn't be fixed

- README.md
- autoload/neoformat/formatters/matlab.vim
- doc/neoformat.txt
Hi guys,
this is a small extension to support ```affenwiesel/matlab-formatter-vscode```
However, I couldn't find a proper place to indicate to the end-user that he should add the "formatter" folder of the above repo in the path. 
Any suggestions?
> support to affenwiesel/matlab-formatter-vscode

- README.md
- autoload/neoformat/formatters/lua.vim
- Add [luafmt](https://github.com/trixnz/lua-fmt) for Lua
- [luaformatter](https://github.com/LuaDevelopmentTools/luaformatter) is inactive and don't support Lua-5.2 or Lua-5.3
Signed-off-by: weiyang <weiyang.ones@gmail.com>
> [Lua] Add 'lua-fmt'

- README.md
- autoload/neoformat/formatters/svelte.vim
- doc/neoformat.txt
Let me know if the README style change should be undone. I blame prettier.
It's technically possible to leave out the `plugin-search-dir` argument if everything is installed globally. But! The svelte compiler is required for the prettier plugin and I don't think most folks install all the svelte compiler globally. This seemed like the most obvious setup.
> Add prettier as svelte formatter

- README.md
- autoload/neoformat/formatters/starlark.vim
- doc/neoformat.txt
Simple starlark scripts can reuse the same bazel formatting scripts.
> Add a starlark formatter

- autoload/neoformat/formatters/pandoc.vim
Pandoc currently formats
```a
into
``` {.a}
which doesn't play well with the rest of Markdown.
> Don't format code block headers into attributes

- README.md
- autoload/neoformat/formatters/reason.vim
- doc/neoformat.txt
This adds the `bsrefmt` formatter to Reason. This is the perferred formatter for Reason BuckleScript projects according to https://bucklescript.github.io/docs/en/installation
> Added `bsrefmt` formatter to Reason

- README.md
- autoload/neoformat/formatters/go.vim
- doc/neoformat.txt
Add go formatter [`gofumpt`](https://github.com/mvdan/gofumpt), [`gofumports`](https://github.com/mvdan/gofumpt).
It is stricter format maintained by one of the members of the Go team.
Thanks for the great work by the way!
> go: add gofumpt

- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/graphql.vim
- autoload/neoformat/formatters/html.vim
- autoload/neoformat/formatters/java.vim
- autoload/neoformat/formatters/javascript.vim
- autoload/neoformat/formatters/json.vim
- autoload/neoformat/formatters/kotlin.vim
- autoload/neoformat/formatters/markdown.vim
- autoload/neoformat/formatters/svelte.vim
- autoload/neoformat/formatters/typescript.vim
- autoload/neoformat/formatters/typescriptreact.vim
- autoload/neoformat/formatters/vue.vim
- autoload/neoformat/formatters/xml.vim
- autoload/neoformat/formatters/yaml.vim
Remove deprecated prettier --stdin option as per https://github.com/prettier/prettier/pull/7668. Resolves #288
> Remove deprecated prettier --stdin option

- autoload/neoformat/formatters/php.vim
Adding the `replace` config setting to the `php-cs-fixer` formatter fixed an issue for me where `php-cs-fixer` was sending a blank file to neoformat's next step (whether it be an additional formatter or the buffer). I'm not quite sure why this was happening, as checking the logs and the temp file that got generated everything seemed fine- so if anyone knows that would be helpful to fix this in a more proper way.
Additionally, I originally thought this was an issue with `phpcbf` since that was the last formatter that got ran and due to the output issue above I was getting the `phpcbf` report saved to my file rather than whatever got formatted. `phpcbf --help` suggests this should be used for `stdin` so I figured it'd be worth adding that while I'm in here.
```
-     Fix STDIN instead of …
```
> Fix php-cs-fixer sending blank file to neoformat

- autoload/neoformat/formatters/r.vim
Neoformat's current invocation to lint R with styler expects sending the
buffer data via stdin. The neoformat 'stdin' variable defaults to 0, so
it does not send the file though via stdin. So set `stdin` to 1.
It still does not work though with `replace = 1` so remove it (so it
then inherits the default 0). Now with `stdin = 1` and `replace`
removed, `:Neoformat` works with styler.
While here, remove an excessive pair of parenthesis in the `args` line.
> Fix R linting with styler

- autoload/neoformat.vim
Updating `&filetype` (even though we are updating it with its current
value), will force Vim to reload syntax, and potentially folds too.
This changes neoformat implementation to only touch `&filetype` if:
- The user called neoformat with a bang (i.e. to force the formatter for
a different filetype)
- The specified filetype was actually different from the current one
Also, this commit also makes sure settings are restored in the **right**
order (i.e. save A, save B, ..., restore B, restore A).
> Don't reset `&filetype`, unless we really have to

- autoload/neoformat/formatters/typescriptreact.vim
'prettiereslint' is already defined for 'typescript' but wasn't defined for 'typescriptreact'. I wasn't sure if I should also add these changes in `README.md` and `doc/neoformat.txt` since it seems that 'javascriptreact' and 'typescriptreact' are not present.
The function was copied from the definition for 'typescript'
> Add 'prettiereslint' as a formatter for 'typescriptreact'

- README.md
- doc/neoformat.txt
- You must use formatter's name without "`-`"
```diff
+  " right
+  let g:neoformat_enabled_haskell = ['sortimports', 'stylishhaskell']
-  " wrong
-  let g:neoformat_enabled_haskell = ['sort-imports', 'stylish-haskell']
```
> update Haskell formatter names to avoid misunderstanding

- README.md
- autoload/neoformat/formatters/erlang.vim
- doc/neoformat.txt
* Adds support for https://github.com/WhatsApp/erlfmt
* Expects `erlfmt` to be available somewhere in user path
> Add erlang erlfmt support

- README.md
- autoload/neoformat/formatters/bib.vim
- doc/neoformat.txt
I needed formatting by bib files and realized it was easy to add support through neoformat. I've followed the procedure described in CONTRIBUTING.md. 
Bib files is a file format for describing references to then be cited in latex documents. Bibclean (https://github.com/tobywf/bibclean) does standard formatting of such files.
> Add [biblean](https://github.com/tobywf/bibclean) support

- README.md
- autoload/neoformat/formatters/zsh.vim
- doc/neoformat.txt
Add support for zsh filetype. Verbatim clone of sh.vim except for function names.
> feat: Add shfmt support for zsh

- autoload/neoformat/formatters/rust.vim
This PR adds support for the variables `shiftwidth`, `textwidth` and `expandtab` to format rust files.
> Add support for rustfmt --config (hard_tabs, max_width and tab_spaces)

- autoload/neoformat/formatters/tex.vim
When using the latest version of `latexindent`, option `-sl` causes the log to be prepended to the formatted file.
> Remove latexindent option '-sl'

- autoload/neoformat/formatters/cmake.vim
Using `/tmp/` prevents cmake-format from picking up `.cmake-format` files, since formatting is done outside the config file tree. Using `stdin` instead solves the issue.
> Send buffer data through stdout to cmake-format

- autoload/neoformat/formatters/tf.vim
Newer tools such as `coc.vim` or `lsp` use the `tf` filetype over `terraform`.
> feat: add tf formatter for terraform

- autoload/neoformat/formatters/rust.vim
rustfmt uses .rustfmt.toml in order to configure its options. By default it will traverse the parent directory chain to look for this file, and if it doesn't find it then it will look in the user's home directory or .config/rustfmt. This feature is useful for projects that want to check a .rustfmt.toml into source control so that formatting is consistent across developers editing code in the repository.
The previous diff #335 checked in defaults that override the .rustfmt.toml config. So neoformat will format rust files differently than the .rustfmt.toml in version control specifies that they should be. A better approach than the previous diff would be to create a .rustfmt.toml in the user's dotfiles if there are options that someone always wants to use when formatting rust code.
Source: …
> Revert #335 which forces rustfmt config options in all cases

- autoload/neoformat.vim
> change to directory of file to allow formatters with config files to find the corresponding config file (e.g. clang-format)

- README.md
- autoload/neoformat.vim
- autoload/neoformat/formatters/bzl.vim
- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/elm.vim
- autoload/neoformat/formatters/graphql.vim
- autoload/neoformat/formatters/html.vim
- autoload/neoformat/formatters/javascript.vim
- autoload/neoformat/formatters/javascriptreact.vim
- autoload/neoformat/formatters/json.vim
- autoload/neoformat/formatters/markdown.vim
- autoload/neoformat/formatters/purescript.vim
- autoload/neoformat/formatters/reason.vim
- autoload/neoformat/formatters/sass.vim
- autoload/neoformat/formatters/scss.vim
- autoload/neoformat/formatters/starlark.vim
- autoload/neoformat/formatters/svelte.vim
- autoload/neoformat/formatters/typescript.vim
- autoload/neoformat/formatters/typescriptreact.vim
- autoload/neoformat/formatters/vue.vim
- autoload/neoformat/formatters/xhtml.vim
- autoload/neoformat/formatters/xml.vim
- autoload/neoformat/formatters/yaml.vim
- doc/neoformat.txt
Many formatters are installed (or can be installed) via `npm`.  When
they are installed for a specific Node project, the executable is placed
in `$project_dir/node_modules/.bin` and is typically *not* on the
`$PATH`.  This change allows Neoformat to look for executables in the
`node_modules/.bin` directory before attempting to use the executable in
the `$PATH`.
For formatters that have `try_node_exe = 1`, and when
`g:neoformat_try_node_exe` is set to `1`, an upward search is performed
beginning at the current directory for `node_modules/.bin/$executable`.
If a match is found, it is used as the executable. If no match is found,
Neoformat will attempt to run the executable as-is.
As part of this change, I set `try_node_exe = 1` on all formatters that
made sense to me -- those related to JS …
> Use node executables in node_modules before $PATH

- README.md
- autoload/neoformat/formatters/json.vim
- autoload/neoformat/formatters/jsonc.vim
- Support `jsonc` so we can do `:Neoformat` on files like `tsconfig.json`
- Remove `--parser json` option since it produces inconsistent format style
> feat: add jsonc support via prettier, remove --parser json option on json

- autoload/neoformat/formatters/bzl.vim
- autoload/neoformat/formatters/starlark.vim
buildifier -h says:
> Buildifier's reformatting depends in part on the path to the file relative
> to the workspace directory. Normally buildifier deduces that path from the
> file names given, but the path can be given explicitly with the -path
> argument. This is especially useful when reformatting standard input,
> or in scripts that reformat a temporary copy of a file.
Indeed without -path, it won't format the files properly. Specify it.
> Specify a file path for buildifier

- README.md
- autoload/neoformat/formatters/toml.vim
- doc/neoformat.txt
> feat(toml): add basic toml support via taplo

- autoload/neoformat/formatters/svelte.vim
See #375. When making changes and then saving an unsaved buffer (like one would do with a BufWritePre autocmd to format on save) on a Svelte file the changes that haven't yet been saved get undone.
I noticed the Svelte formatter used a different order of prettier arguments than all of the other formatters that use prettier. The `--stdin-filepath` argument had a couple other arguments before the file path. I reordered them so the file path immediately follows `--stdin-filepath` and that seems to have fixed the issue for me.
I'm pretty sure what's happening is that Prettier ignores the buffer passed as stdin because it doesn't see the file path in the arguments as the value to `--stdin-filepath`, but instead as the file path to the file to format, so it just ignores the buffer text sent …
> Fixed the order of arguments for Prettier with svelte

- README.md
- autoload/neoformat/formatters/ebuild.vim
[ebuild](https://wiki.gentoo.org/wiki/Ebuild) is like bash script but with minor differences, and `shfmt` can correctly format it
> add shfmt fromatter for ebuild

- README.md
- autoload/neoformat/formatters/css.vim
- autoload/neoformat/formatters/graphql.vim
- autoload/neoformat/formatters/html.vim
- autoload/neoformat/formatters/java.vim
- autoload/neoformat/formatters/javascript.vim
- autoload/neoformat/formatters/javascriptreact.vim
- autoload/neoformat/formatters/json.vim
- autoload/neoformat/formatters/jsonc.vim
- autoload/neoformat/formatters/kotlin.vim
- autoload/neoformat/formatters/less.vim
- autoload/neoformat/formatters/markdown.vim
- autoload/neoformat/formatters/php.vim
- autoload/neoformat/formatters/scss.vim
- autoload/neoformat/formatters/solidity.vim
- autoload/neoformat/formatters/svelte.vim
- autoload/neoformat/formatters/typescript.vim
- autoload/neoformat/formatters/typescriptreact.vim
- autoload/neoformat/formatters/vue.vim
- autoload/neoformat/formatters/xml.vim
- autoload/neoformat/formatters/yaml.vim
- doc/neoformat.txt
Closes https://github.com/sbdchd/neoformat/issues/373
This PR adds [`prettierd`](https://github.com/fsouza/prettierd) to the available formatters.
- Everywhere that prettier was present, there is now also an entry for prettierd.
- prettierd is preferred over prettier, when it is installed.
In some cases, the arguments passed to prettier include additional options (e.g., [vue](https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/svelte.vim)). **I did not try to preserve those options in the prettierd flags.** I'm not sure if this will cause problems for anyone; those options haven't been needed in my use cases yet.
> Add prettierd

- autoload/neoformat/formatters/ebuild.vim
- autoload/neoformat/formatters/sh.vim
- autoload/neoformat/formatters/zsh.vim
If `expandtab` is not set, do not pass `shiftwidth` to shfmt. shfmt uses tabs by default.
> Fix tabs in shfmt

- README.md
- autoload/neoformat/formatters/yaml.vim
- doc/neoformat.txt
`yamlfmt` is an opionated yaml formatter, and it supports keeping comments.
https://github.com/mmlb/yamlfmt
> feat: add yamlfmt support for YAML

- autoload/neoformat/formatters/php.vim
Laravel Pint is not shown as an option. This change adds an entry for Pint to the list shown to the user.
> fix: laravel pint not shown as an option

- autoload/neoformat.vim
Should set to true the second parameter {nosuf}
see `:help expand`
otherways it return empty string if 'wildignore' contains `**/tmp/**`
> Wrong usage of expand function

- autoload/neoformat/formatters/systemverilog.vim
- autoload/neoformat/formatters/verilog.vim
verible-verilog-format is a tool for formatting Verilog and SystemVerilog code. Part of the Verible tool suite.
The more detailed information, you can refer to https://chipsalliance.github.io/verible/ . Thanks.
> feat: add verible-verilog-format as verilog and system verilog formatter

- README.md
- autoload/neoformat/formatters/caddyfile.vim
1. add caddyfile related information to README
2. fix an error that `caddy fmt` cannot read file content correctly
> doc: add caddyfile related info to README.md

- autoload/neoformat/formatters/solidity.vim
There were two different problems:
* `forge fmt` does support stdin, by sending `-` instead of a path. I assume this is a better approach?
* the `--check` flag causes `forge` to send an exit code `1` when invalid syntax is found. However, it also causes it to not send any output, resulting in the buffer becoming empty. Removing this flag fixes it, and also makes `valid_exit_codes` unnecessary
> Fixing solidity/forge integration

- autoload/neoformat/formatters/c.vim
Otherwise, it fails with filenames with spaces.
> escape character in clangd fix

- README.md
- autoload/neoformat/formatters/xml.vim
- doc/neoformat.txt
Add the XML parser xmllint from libxml2. This parser is included with libxml2 which is a core dependency for a few Linux distros so it's probably a good idea to include it as a fallback option.
Signed-off-by: StaticRocket <35777938+StaticRocket@users.noreply.github.com>
> feat: xml: add xmllint parser

- autoload/neoformat/formatters/javascript.vim
- autoload/neoformat/formatters/javascriptreact.vim
- autoload/neoformat/formatters/json.vim
- autoload/neoformat/formatters/jsonc.vim
- autoload/neoformat/formatters/typescript.vim
- autoload/neoformat/formatters/typescriptreact.vim
Deno changed the default behavior for fmt calls using stdin content. By default it assumes all input is TypeScript and otherwise it needs to be specified by the --ext option. This adds the appropriate --ext flags for all file types associated with Deno (except markdown since that was added in an earlier).
Signed-off-by: StaticRocket <35777938+StaticRocket@users.noreply.github.com>
> fix: add content type to deno fmt calls

- README.md
- autoload/neoformat/formatters/tex.vim
Hi!
This change makes easier to use `latexindent` with `-m` flag, that allows the formatter to modify linebreaks, and of course makes it possible to add some other parameters that might be useful for the final user.
Thanks!
> feat(latexindent): add `opts` array to modify params

- README.md
- autoload/neoformat/formatters/ruby.vim
- doc/neoformat.txt
- https://github.com/testdouble/standard is an opinionated wrapper around rubocop.
- Update documentation for ruby#standard
- Also use the current repo URL for rubocop
> Add support for standardrb formatter

- README.md
- autoload/neoformat/formatters/fennel.vim
This adds support for [fennel](https://fennel-lang.org) using [`fnlfmt`](https://fennel-lang.org/style). Let me know if I missed anything to add this!
> Add fennel support

- README.md
- autoload/neoformat/formatters/bib.vim
- doc/neoformat.txt
This PR brings a new (more modern) formatter for Bibtex entries.
All the info for the required formatter (how to install, etc) is on the official docs of  [bibtex-tidy](https://github.com/FlamingTempura/bibtex-tidy)
https://user-images.githubusercontent.com/21349875/231716380-88489c1b-4c82-45a7-a047-eb2d39fe1487.mov
> Add bibtex modern formatter

- autoload/neoformat/formatters/c.vim
`clang-format` receives file name without the path part in the `-assume-file` parameter and thus isn't able to find the style config closest to the file's location. For a file `subproject/main.c` it will use `./.clang-format` instead of `subproject/.clang-format`. Change the parameter to `%` instead of `%:t` to receive full path for the file being formatted. 
Fixes #459
> Use full path with clang-format

- README.md
- autoload/neoformat/formatters/hcl.vim
- doc/neoformat.txt
This adds support for [hcl](https://github.com/hashicorp/hcl) using [`hclfmt`](https://github.com/hashicorp/hcl/tree/main/cmd/hclfmt).
> Add HCL support

- README.md
- autoload/neoformat/formatters/rego.vim
- doc/neoformat.txt
This adds support for [rego](https://www.openpolicyagent.org/docs/latest/policy-language/) using [`opa fmt`](https://www.openpolicyagent.org/docs/latest/cli/#opa-fmt).
> Add `Rego` support

- README.md
- autoload/neoformat/formatters/yaml.vim
- doc/neoformat.txt
Add the yamlfix formatter. It's also python based but it preserves comments and formats things a little closer to what yamllint wants.
> yaml: add yamlfix formatter

- README.md
- autoload/neoformat/formatters/javascript.vim
- autoload/neoformat/formatters/javascriptreact.vim
- autoload/neoformat/formatters/json.vim
- autoload/neoformat/formatters/jsonc.vim
- autoload/neoformat/formatters/typescript.vim
- autoload/neoformat/formatters/typescriptreact.vim
- doc/neoformat.txt
This PR adds support for [Biome](https://biomejs.dev/) to the `javascript`, `javascriptreact`, `typescript`, `typescriptreact`, `json`, and `jsonc` file types.
> Add Biomeformatter for JavaScript, TypeScript, React, JSON, and JSONC

- autoload/neoformat/formatters/typescript.vim
Without this, I get this error:
```
Error detected while processing BufReadPost Autocommands for "*":                                                                                                                                                                                                                                                                                                                              
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:35: Error executing lua: /usr/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[20]..script /home/benjie/.local/share/nvim/site/pack/packer/start/local-npm-bin.vim/ftplugin/typescript.vim[20]../home/benjie/.local/share/nvim/site/pack …
```
> Fix biome formatter function name in TypeScript

- README.md
- autoload/neoformat/formatters/typst.vim
- doc/neoformat.txt
I added two formatters for Typst, `typstfmt` and `typstyle`. I also updated `README.md` and `doc/neoformat.txt`.
> Add Typst formatters

- README.md
- autoload/neoformat/formatters/eruby.vim
- doc/neoformat.txt
HTMLBeautifier (https://github.com/threedaymonk/htmlbeautifier) can format eruby files (.html.erb). 
The code is copied from here: https://github.com/sbdchd/neoformat/issues/255 .
I've tested it from my Mac.
For new users who just arrived at this repo: you need to install htmlbeautifier program first (`gem install htmlbeautifier`), and then run :Neoformat in vim.
> Add support for eruby.

- autoload/neoformat/formatters/haskell.vim
Ormolu requires this flag since version 0.5.0.0 (released on 2022-05-12) to identify the associated cabal file.
> Add the required `--stdin-input-file` flag to ormolu

- autoload/neoformat/formatters/typst.vim
Fixed an issue where `typst` would be seen as formatter instead of `typstfmt`.
> `typstfmt` successfully works now

- autoload/neoformat/formatters/cabal.vim
`cabal-fmt` supports pragmas, all of which are [currently undocumented](https://github.com/phadej/cabal-fmt/issues/35), some of which (e.g. `expand`) only work when given the original file path.
This PR makes `cabal-fmt` run on the original file instead of a temporary one.
> Give cabal-fmt access to the filename

- autoload/neoformat/formatters/cs.vim
Adds the 'format' parameter required for csharpier v1.x
Is a fix for this issue:
https://github.com/sbdchd/neoformat/issues/506
> fix: add 'format' param required for csharpier v1.x

- autoload/neoformat/formatters/beancount.vim
Beancount's `bean-format` requires a filename as argument in version 3. Pass `-` to read from stdin, which happens to be compatible with `bean-format` for Beancount 2.
> Invoke bean-format with '-' to be compatible with Beancount 2 and 3
