autoload/neoformat/formatters/pandoc.vim
This correctly handles:
- Table of contents
- YAML front matter
=> Extend Pandoc formatter

autoload/neoformat/formatters/haskell.vim
A handy-dandy Haskell code formatter.
=> add hindent

README.md, autoload/neoformat/formatters/haskell.vim, doc/neoformat.txt
=> Add `hfmt`

.travis.yml, autoload/neoformat.vim, test/after/tsfmt.ts, test/before/tsfmt.ts, test/install.sh, test/vimrc
Now using `split(system(), '\n')` instead of `systemlist()`
=> Fixed issue with line endings and formatters

README.md, autoload/neoformat/formatters/javascript.vim, doc/neoformat.txt
This works with the https://www.npmjs.com/package/prettier-eslint-cli package, and seems to handle the eslint configuration fine.
=> add prettier-eslint formatter

README.md, autoload/neoformat/formatters/json.vim, doc/neoformat.txt
https://stedolan.github.io/jq/
Available in Ubuntu & Debian repositories too.
=> Add jq as JSON formatter

README.md, autoload/neoformat/formatters/scala.vim
* Add scalafmt to the scala formatter file
* Add scalafmt to the supported formatters on the README file
=> Add scalafmt to scala formatters

autoload/neoformat.vim
See https://github.com/sbdchd/neoformat/issues/50
=> Updated temp file name creation to use tempname()

README.md, autoload/neoformat/formatters/python.vim, doc/neoformat.txt
=> Add `isort` formatter for Python

autoload/neoformat.vim
Fixes https://github.com/sbdchd/neoformat/issues/77
=> Allow buffer local formatter configuration

autoload/neoformat/formatters/typescript.vim
Add typescript prettier support
=> Add typescript prettier support

README.md, autoload/neoformat.vim, doc/neoformat.txt, test/neoformat.vader
=> Add support for running multiple formatters

autoload/neoformat/formatters/json.vim
=> Add prettier formatter for json

autoload/neoformat/formatters/html.vim
=> html-tidy formatter fix

README.md, autoload/neoformat/formatters/kotlin.vim, doc/neoformat.txt
https://github.com/shyiko/ktlint
=> Adds support for kotlin using ktlint.

autoload/neoformat/formatters/c.vim, autoload/neoformat/formatters/cpp.vim, autoload/neoformat/formatters/cs.vim, autoload/neoformat/formatters/objc.vim, autoload/neoformat/formatters/pawn.vim
should not pass `-f` to uncrustify since `'stdin'` was set to `1`.
=> fix uncrustify formatters

autoload/neoformat/formatters/pandoc.vim
this flag was removed in the latest pandoc
=> rm deprecated flag

README.md, autoload/neoformat/formatters/ocaml.vim, doc/neoformat.txt
[ocamlformat](https://github.com/ocaml-ppx/ocamlformat) is a new tool for format ocaml.
=> Adds support for ocaml using ocamlformat.

README.md, autoload/neoformat.vim, doc/neoformat.txt
Adds inline ENV support as discussed in #128.
Works locally for me on the example given in the issue.
My Vimscript-Fu is not super strong, so just feel free to do whatever ;-)
=> Inline environment variable support

README.md, autoload/neoformat/formatters/markdown.vim, doc/neoformat.txt
See https://github.com/prettier/prettier/releases/tag/1.8.0
=> Add prettier as a markdown formatter too

README.md, autoload/neoformat/formatters/python.vim, doc/neoformat.txt
For making docstrings prettier.
=> Add docformatter

README.md, autoload/neoformat/formatters/python.vim, doc/neoformat.txt
Black is a new but already popular and promising formatter for python https://github.com/ambv/black.
=> Add `black` as python formatter

README.md, autoload/neoformat/formatters/vue.vim, doc/neoformat.txt
`prettier` supports vue, this commit proposes to handle the vue filetype.
=> Add `prettier` as vue formatter

autoload/neoformat/formatters/python.vim
Backslashes are ugly and trailing commas give prettier diffs.
=> Improve isort options

README.md, autoload/neoformat/formatters/swift.vim, doc/neoformat.txt
I would like to add Swiftformat.
=> Add Swift formatter

autoload/neoformat.vim
=> fix error output for windows

README.md, autoload/neoformat/formatters/sql.vim, doc/neoformat.txt
This is not a complete tool, but it does have decent support for basic
MySQL, so I put it last in the priority list.
=> Add sqlfmt

autoload/neoformat/formatters/pandoc.vim
Pandoc now has task list support, so the hacking with sed isn't necessary
anymore.
=> Add support for new pandoc checklists

README.md, autoload/neoformat/formatters/sbt.vim, doc/neoformat.txt
* Add sbt support via scalafmt
* Update scala formatters in txt doc
=> Add sbt support via scalafmt

README.md, autoload/neoformat/formatters/haskell.vim, doc/neoformat.txt
Add [floskell](https://github.com/ennocramer/floskell) as a haskell formatter
Tagging @ennocramer 😄
=> Add floskell as a haskell formatter

README.md, autoload/neoformat/formatters/dune.vim, doc/neoformat.txt
See https://github.com/ocaml/dune/pull/1821
=> Add formatter for dune files

README.md, autoload/neoformat/formatters/r.vim, doc/neoformat.txt
First of all, thanks a lot for this wonderful plugin
I would like add styler as R formmater
Don't hesitate to request  for anything
I hope to be useful
Thanks a lot again
=> Add styler as R formatter

autoload/neoformat/formatters/typescript.vim
Enabled through this project:
https://github.com/typescript-eslint/typescript-eslint
=> Allow using eslint_d for typescript

autoload/neoformat/formatters/typescript.vim
=> Only include tslint.json if it exists

README.md, autoload/neoformat/formatters/purescript.vim, doc/neoformat.txt
https://gitlab.com/joneshf/purty
=> Add purty PureScript formatter

autoload/neoformat/formatters/c.vim, autoload/neoformat/formatters/java.vim, autoload/neoformat/formatters/javascript.vim, autoload/neoformat/formatters/typescript.vim
=> Set `-assume-filename` option to detect the language

README.md, autoload/neoformat/formatters/nix.vim, doc/neoformat.txt
Adds support for `nixfmt`, which formats `.nix` files.
=> Add support for `nixfmt`

autoload/neoformat/formatters/haskell.vim
=> Fix ormolu options

README.md, autoload/neoformat/formatters/sh.vim
Signed-off-by: Jo Vandeginste <Jo.Vandeginste@kuleuven.be>
=> Add an option to customize shfmt behaviour

README.md, autoload/neoformat/formatters/java.vim, autoload/neoformat/formatters/kotlin.vim, autoload/neoformat/formatters/xml.vim
=> Add Prettier formatters for Kotlin, Java, and XML

README.md, autoload/neoformat/formatters/nginx.vim, doc/neoformat.txt
This adds support for [nginxbeautifier](https://github.com/vasilevich/nginxbeautifier)
=> Add support for nginxbeautifier

README.md, autoload/neoformat/formatters/gleam.vim, doc/neoformat.txt
Gleam: https://github.com/gleam-lang/gleam/
Thank you!
=> Add support for Gleam

README.md, autoload/neoformat/formatters/powershell.vim, doc/neoformat.txt
=> [PowerShell] add PowerShell-Beautifier.

README.md, autoload/neoformat/formatters/javascript.vim, autoload/neoformat/formatters/typescript.vim
This adds support for [deno fmt](https://deno.land/manual/tools/formatter)
=> Add support for deno fmt

README.md, autoload/neoformat/formatters/cabal.vim, doc/neoformat.txt
=> Add support for cabal files through cabal-fmt

autoload/neoformat/formatters/typescriptreact.vim
going forward it might be a good idea to introduce some kind of
aliasing, but for now I hope this will do.
=> adding support for typescriptreact filetype (#279)

README.md, autoload/neoformat/formatters/beancount.vim, doc/neoformat.txt
* Update the link for the `black` formatter
* Add readme and doc format update step
* Add support for beancount via `bean-format`
=> Add support for beancount and minor doc updates

autoload/neoformat/formatters/haskell.vim
=> Remove unused flag from ormolu

.kodiak.toml
Setup kodiak for easier merging
=> add(ci): kodiak config

README.md, autoload/neoformat/formatters/dart.vim, doc/neoformat.txt
Title.  Did this locally and it works well.
=> Add dart format because dartfmt is deprecated in newer dart sdks

autoload/neoformat.vim
=> revert: cwd change

README.md, autoload/neoformat/sugarss.vim, doc/neoformat.txt
[SugarSS](https://github.com/postcss/sugarss) is an “indent-based CSS syntax for PostCSS”
=> SugarSS support

README.md, autoload/neoformat/formatters/php.vim, doc/neoformat.txt
I added prettier to the PHP formatters as prettier also works with PHP with the [php-plugin](https://github.com/prettier/plugin-php).
=> Add prettier to php formatters

README.md, autoload/neoformat/formatters/nix.vim, doc/neoformat.txt
This PR adds support for the `alejandra` formatter for the `nix` language
- Fixes #402
=> Add Alejandra formatter

README.md, autoload/neoformat/formatters/zig.vim, doc/neoformat.txt
added file reader
zig format fix
=> Added a new formatter for Zig because previous one was slow AF!

README.md, autoload/neoformat/formatters/blade.vim
Handler for blade templates (used in the Laravel framework)
https://github.com/shufo/blade-formatter
=> feat: add blade-formatter

autoload/neoformat/formatters/opencl.vim
…dded some extra key words ...
=> add: support opencl language which is a subset of C language and is added some additional keywords

README.md, autoload/neoformat/formatters/cs.vim, doc/neoformat.txt
`csharpier` is an opinionated formatter for csharp.
[CSharpier](https://csharpier.com/)
=> feat: Added support for csharpier

README.md, autoload/neoformat/formatters/htmldjango.vim, doc/neoformat.txt
Formatter for Django HTML templates.
[djlint](https://www.djlint.com/)
=> feat: add htmldjano filetype and formatter

README.md, autoload/neoformat/formatters/solidity.vim
See title, forge is pretty standard these days and at least a very common solidity tool, and they have a formatter. This should allow users to format their solidity with forge
=> Add forge as solidity formatter

README.md, autoload/neoformat/formatters/astro.vim, doc/neoformat.txt
adds prettier support for [astro](https://astro.build/) framework
=> feat: add prettier as astro formatter

autoload/neoformat/formatters/blade.vim
see issue https://github.com/sbdchd/neoformat/issues/448
=> Fix: blade formatter

README.md, autoload/neoformat/formatters/sql.vim, doc/neoformat.txt
This adds [`sleek`](https://github.com/nrempel/sleek) as SQL formatter.
=> Add `sleek` as sql formatter

README.md, autoload/neoformat/formatters/json.vim, autoload/neoformat/formatters/nickel.vim, autoload/neoformat/formatters/ocaml.vim, autoload/neoformat/formatters/rust.vim, autoload/neoformat/formatters/sh.vim, autoload/neoformat/formatters/toml.vim, doc/neoformat.txt
Site: https://topiary.tweag.io
fixes #468
Working for me locally against OCaml, TOML, and Nickel files.
---
User/contributor toastal wishes this repository was mirrored away from the US proprietary control of Microsoft™ GitHub so users can contribute with privacy & freedom.
=> add multi-language formatter: topiary

autoload/neoformat/formatters/swift.vim
This adds [`swift-format`](https://github.com/apple/swift-format) as a formatter for Swift files.
=> Add swift-format for Swift files

README.md, autoload/neoformat/formatters/objcpp.vim, doc/neoformat.txt
Add definition for Objective C++ files for uncrustify, clang-format and astyle
=> Add support for Objective C++

README.md, autoload/neoformat/formatters/python.vim, doc/neoformat.txt
Add python ruff formatter support
https://github.com/astral-sh/ruff
=> Python ruff formatter

README.md, autoload/neoformat/formatters/yaml.vim, doc/neoformat.txt
See https://github.com/google/yamlfmt
Sadly it is called exactly the same like the tool that was developed by @mmlb that is already supported by Neoformat.
=> Add google's yamlfmt formatter

autoload/neoformat/formatters/nim.vim
Add nph as another formatter for nim lang.
nph is an opinionated code formatter for Nim
https://github.com/arnetheduck/nph
=> add nph as nim formatter

README.md
Add nph as nim formatter in README.md 
https://github.com/sbdchd/neoformat/pull/491
=> Add nim nph formatter to README.md

README.md, autoload/neoformat/formatters/just.vim
Format justfiles using `just` itself.
=> Add support for just

README.md, autoload/neoformat/formatters/css.vim, autoload/neoformat/formatters/json.vim, autoload/neoformat/formatters/nickel.vim, autoload/neoformat/formatters/ocaml.vim, autoload/neoformat/formatters/rust.vim, autoload/neoformat/formatters/sh.vim, autoload/neoformat/formatters/toml.vim
With later versions of Topiary, CSS support was added as well as a new way to merge configuration.
Can read/review commit by commit.
[^1]
[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.
=> Topiary updates

README.md, autoload/neoformat/formatters/sql.vim, doc/neoformat.txt
Add [sql-formatter](https://github.com/sql-formatter-org/sql-formatter)
=> add sql-formatter

README.md, autoload/neoformat/formatters/kdl.vim, doc/neoformat.txt
https://kdl.dev/
https://github.com/hougesen/kdlfmt/
[^1]
[^1]: Please consider [giving up MS GitHub](https://sfconservancy.org/GiveUpGitHub/) or offering a non-proprietary, non-US-corporate-controlled mirror for this free software project. I wish to delete this Microsoft account in the future, but I need more projects like this to support alternative methods to send patches & contribute.
=> add KDL support with kdlfmt
